BEGIN;

CREATE TABLE card_products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    bank_id BIGINT NOT NULL,
    name VARCHAR(150) NOT NULL,
    card_type VARCHAR(50) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_card_products_bank
        FOREIGN KEY (bank_id)
        REFERENCES banks(id)
);

CREATE UNIQUE INDEX uk_card_products_bank_name_lower
    ON card_products (bank_id, LOWER(name));

CREATE INDEX idx_card_products_bank_id
    ON card_products (bank_id);

ALTER TABLE cards
    ADD COLUMN card_product_id BIGINT;

ALTER TABLE cards
    ADD CONSTRAINT fk_cards_card_product
        FOREIGN KEY (card_product_id)
        REFERENCES card_products(id);

CREATE INDEX idx_cards_card_product_id
    ON cards (card_product_id);

COMMIT;