BEGIN;

CREATE TABLE saved_offers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    offer_id BIGINT NOT NULL,

    CONSTRAINT fk_saved_offers_user
        FOREIGN KEY (user_id)
        REFERENCES users(id),

    CONSTRAINT fk_saved_offers_offer
        FOREIGN KEY (offer_id)
        REFERENCES offers(id)
);

CREATE UNIQUE INDEX uk_saved_offers_user_offer
    ON saved_offers (user_id, offer_id);

CREATE INDEX idx_saved_offers_user_id
    ON saved_offers(user_id);

CREATE INDEX idx_saved_offers_offer_id
    ON saved_offers(offer_id);

COMMIT;