spring.application.name=backend

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/linkvault
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.open-in-view=false

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=900000